var group__require__eigens__types =
[
    [ "arena_matrix", "group__arena__matrix__types.html", "group__arena__matrix__types" ],
    [ "dense_dynamic", "group__dense__dynamic__types.html", "group__dense__dynamic__types" ],
    [ "eigen", "group__eigen__types.html", "group__eigen__types" ],
    [ "eigen_array", "group__eigen__array__types.html", "group__eigen__array__types" ],
    [ "eigen_matrix_or_array", "group__eigen__matrix__or__array__types.html", "group__eigen__matrix__or__array__types" ],
    [ "eigen_contiguous_map", "group__eigen__contiguous__map__types.html", "group__eigen__contiguous__map__types" ],
    [ "eigen_dense_base", "group__eigen__dense__base__types.html", "group__eigen__dense__base__types" ],
    [ "eigen_dense_dynamic", "group__eigen__dense__dynamic__types.html", "group__eigen__dense__dynamic__types" ],
    [ "eigen_matrix_dynamic", "group__eigen__matrix__dynamic__types.html", "group__eigen__matrix__dynamic__types" ],
    [ "eigen_matrix_base", "group__eigen__matrix__base__types.html", "group__eigen__matrix__base__types" ],
    [ "eigen_sparse_base", "group__eigen__sparse__base__types.html", "group__eigen__sparse__base__types" ],
    [ "matrix", "group__matrix__types.html", "group__matrix__types" ],
    [ "plain_type", "group__plain__type__types.html", "group__plain__type__types" ],
    [ "rev_matrix", "group__rev__matrix__types.html", "group__rev__matrix__types" ],
    [ "rev_col_vector", "group__rev__col__vector__types.html", "group__rev__col__vector__types" ],
    [ "rev_row_vector", "group__rev__row__vector__types.html", "group__rev__row__vector__types" ],
    [ "rev_vector", "group__rev__vector__types.html", "group__rev__vector__types" ],
    [ "var_dense_dynamic", "group__var__dense__dynamic__types.html", "group__var__dense__dynamic__types" ],
    [ "var_eigen", "group__var__eigen__types.html", "group__var__eigen__types" ],
    [ "var_matrix", "group__var__matrix__types.html", "group__var__matrix__types" ],
    [ "var_col_vector", "group__var__col__vector__types.html", "group__var__col__vector__types" ],
    [ "var_row_vector", "group__var__row__vector__types.html", "group__var__row__vector__types" ],
    [ "var_vector", "group__var__vector__types.html", "group__var__vector__types" ],
    [ "eigen_col_vector", "group__eigen__col__vector__types.html", "group__eigen__col__vector__types" ],
    [ "col_vector", "group__col__vector__types.html", "group__col__vector__types" ],
    [ "eigen_row_vector", "group__eigen__row__vector__types.html", "group__eigen__row__vector__types" ],
    [ "row_vector", "group__row__vector__types.html", "group__row__vector__types" ],
    [ "eigen_vector", "group__eigen__vector__types.html", "group__eigen__vector__types" ]
];