var searchData=
[
  ['gamma_5fccdf_5flog_2ehpp_6742',['gamma_ccdf_log.hpp',['../gamma__ccdf__log_8hpp.html',1,'']]],
  ['gamma_5fcdf_2ehpp_6743',['gamma_cdf.hpp',['../gamma__cdf_8hpp.html',1,'']]],
  ['gamma_5fcdf_5flog_2ehpp_6744',['gamma_cdf_log.hpp',['../gamma__cdf__log_8hpp.html',1,'']]],
  ['gamma_5flccdf_2ehpp_6745',['gamma_lccdf.hpp',['../gamma__lccdf_8hpp.html',1,'']]],
  ['gamma_5flcdf_2ehpp_6746',['gamma_lcdf.hpp',['../gamma__lcdf_8hpp.html',1,'']]],
  ['gamma_5flog_2ehpp_6747',['gamma_log.hpp',['../gamma__log_8hpp.html',1,'']]],
  ['gamma_5flpdf_2ehpp_6748',['gamma_lpdf.hpp',['../opencl_2prim_2gamma__lpdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2gamma__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['gamma_5fp_2ehpp_6749',['gamma_p.hpp',['../fwd_2fun_2gamma__p_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2gamma__p_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2gamma__p_8hpp.html',1,'(Global Namespace)']]],
  ['gamma_5fq_2ehpp_6750',['gamma_q.hpp',['../fwd_2fun_2gamma__q_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2gamma__q_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2gamma__q_8hpp.html',1,'(Global Namespace)']]],
  ['gamma_5frng_2ehpp_6751',['gamma_rng.hpp',['../gamma__rng_8hpp.html',1,'']]],
  ['gaussian_5fdlm_5fobs_5flog_2ehpp_6752',['gaussian_dlm_obs_log.hpp',['../gaussian__dlm__obs__log_8hpp.html',1,'']]],
  ['gaussian_5fdlm_5fobs_5flpdf_2ehpp_6753',['gaussian_dlm_obs_lpdf.hpp',['../gaussian__dlm__obs__lpdf_8hpp.html',1,'']]],
  ['gaussian_5fdlm_5fobs_5frng_2ehpp_6754',['gaussian_dlm_obs_rng.hpp',['../gaussian__dlm__obs__rng_8hpp.html',1,'']]],
  ['generalized_5finverse_2ehpp_6755',['generalized_inverse.hpp',['../prim_2fun_2generalized__inverse_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2generalized__inverse_8hpp.html',1,'(Global Namespace)']]],
  ['get_2ehpp_6756',['get.hpp',['../get_8hpp.html',1,'']]],
  ['get_5fbase1_2ehpp_6757',['get_base1.hpp',['../get__base1_8hpp.html',1,'']]],
  ['get_5fbase1_5flhs_2ehpp_6758',['get_base1_lhs.hpp',['../get__base1__lhs_8hpp.html',1,'']]],
  ['get_5fimag_2ehpp_6759',['get_imag.hpp',['../get__imag_8hpp.html',1,'']]],
  ['get_5fkernel_5fsource_5ffor_5fevaluating_5finto_2ehpp_6760',['get_kernel_source_for_evaluating_into.hpp',['../get__kernel__source__for__evaluating__into_8hpp.html',1,'']]],
  ['get_5flp_2ehpp_6761',['get_lp.hpp',['../get__lp_8hpp.html',1,'']]],
  ['get_5freal_2ehpp_6762',['get_real.hpp',['../get__real_8hpp.html',1,'']]],
  ['getting_5fstarted_2emd_6763',['getting_started.md',['../getting__started_8md.html',1,'']]],
  ['gevv_5fvvv_5fvari_2ehpp_6764',['gevv_vvv_vari.hpp',['../gevv__vvv__vari_8hpp.html',1,'']]],
  ['gp_5fdot_5fprod_5fcov_2ehpp_6765',['gp_dot_prod_cov.hpp',['../opencl_2prim_2gp__dot__prod__cov_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2gp__dot__prod__cov_8hpp.html',1,'(Global Namespace)']]],
  ['gp_5fexp_5fquad_5fcov_2ehpp_6766',['gp_exp_quad_cov.hpp',['../opencl_2kernels_2gp__exp__quad__cov_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2gp__exp__quad__cov_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2gp__exp__quad__cov_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2gp__exp__quad__cov_8hpp.html',1,'(Global Namespace)']]],
  ['gp_5fexponential_5fcov_2ehpp_6767',['gp_exponential_cov.hpp',['../opencl_2kernels_2gp__exponential__cov_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2gp__exponential__cov_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2gp__exponential__cov_8hpp.html',1,'(Global Namespace)']]],
  ['gp_5fmatern32_5fcov_2ehpp_6768',['gp_matern32_cov.hpp',['../opencl_2kernels_2gp__matern32__cov_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2gp__matern32__cov_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2gp__matern32__cov_8hpp.html',1,'(Global Namespace)']]],
  ['gp_5fmatern52_5fcov_2ehpp_6769',['gp_matern52_cov.hpp',['../opencl_2kernels_2gp__matern52__cov_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2gp__matern52__cov_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2gp__matern52__cov_8hpp.html',1,'(Global Namespace)']]],
  ['gp_5fperiodic_5fcov_2ehpp_6770',['gp_periodic_cov.hpp',['../prim_2fun_2gp__periodic__cov_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2gp__periodic__cov_8hpp.html',1,'(Global Namespace)']]],
  ['grad_2ehpp_6771',['grad.hpp',['../core_2grad_8hpp.html',1,'(Global Namespace)'],['../fun_2grad_8hpp.html',1,'(Global Namespace)']]],
  ['grad_5f2f1_2ehpp_6772',['grad_2F1.hpp',['../grad__2_f1_8hpp.html',1,'']]],
  ['grad_5ff32_2ehpp_6773',['grad_F32.hpp',['../grad___f32_8hpp.html',1,'']]],
  ['grad_5fhessian_2ehpp_6774',['grad_hessian.hpp',['../grad__hessian_8hpp.html',1,'']]],
  ['grad_5finc_5fbeta_2ehpp_6775',['grad_inc_beta.hpp',['../fwd_2fun_2grad__inc__beta_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2grad__inc__beta_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2grad__inc__beta_8hpp.html',1,'(Global Namespace)']]],
  ['grad_5fpfq_2ehpp_6776',['grad_pFq.hpp',['../grad__p_fq_8hpp.html',1,'']]],
  ['grad_5freg_5finc_5fbeta_2ehpp_6777',['grad_reg_inc_beta.hpp',['../grad__reg__inc__beta_8hpp.html',1,'']]],
  ['grad_5freg_5finc_5fgamma_2ehpp_6778',['grad_reg_inc_gamma.hpp',['../grad__reg__inc__gamma_8hpp.html',1,'']]],
  ['grad_5freg_5flower_5finc_5fgamma_2ehpp_6779',['grad_reg_lower_inc_gamma.hpp',['../grad__reg__lower__inc__gamma_8hpp.html',1,'']]],
  ['grad_5ftr_5fmat_5ftimes_5fhessian_2ehpp_6780',['grad_tr_mat_times_hessian.hpp',['../grad__tr__mat__times__hessian_8hpp.html',1,'']]],
  ['gradient_2ehpp_6781',['gradient.hpp',['../fwd_2functor_2gradient_8hpp.html',1,'(Global Namespace)'],['../rev_2functor_2gradient_8hpp.html',1,'(Global Namespace)']]],
  ['gradient_5fdot_5fvector_2ehpp_6782',['gradient_dot_vector.hpp',['../gradient__dot__vector_8hpp.html',1,'']]],
  ['gumbel_5fccdf_5flog_2ehpp_6783',['gumbel_ccdf_log.hpp',['../gumbel__ccdf__log_8hpp.html',1,'']]],
  ['gumbel_5fcdf_2ehpp_6784',['gumbel_cdf.hpp',['../opencl_2prim_2gumbel__cdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2gumbel__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['gumbel_5fcdf_5flog_2ehpp_6785',['gumbel_cdf_log.hpp',['../gumbel__cdf__log_8hpp.html',1,'']]],
  ['gumbel_5flccdf_2ehpp_6786',['gumbel_lccdf.hpp',['../opencl_2prim_2gumbel__lccdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2gumbel__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['gumbel_5flcdf_2ehpp_6787',['gumbel_lcdf.hpp',['../opencl_2prim_2gumbel__lcdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2gumbel__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['gumbel_5flog_2ehpp_6788',['gumbel_log.hpp',['../gumbel__log_8hpp.html',1,'']]],
  ['gumbel_5flpdf_2ehpp_6789',['gumbel_lpdf.hpp',['../opencl_2prim_2gumbel__lpdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2gumbel__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['gumbel_5frng_2ehpp_6790',['gumbel_rng.hpp',['../gumbel__rng_8hpp.html',1,'']]]
];
