var searchData=
[
  ['lambert_5fw_2ehpp_6943',['lambert_w.hpp',['../fwd_2fun_2lambert__w_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2lambert__w_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2lambert__w_8hpp.html',1,'(Global Namespace)']]],
  ['lb_5fconstrain_2ehpp_6944',['lb_constrain.hpp',['../opencl_2prim_2lb__constrain_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2lb__constrain_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2lb__constrain_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2lb__constrain_8hpp.html',1,'(Global Namespace)']]],
  ['lb_5ffree_2ehpp_6945',['lb_free.hpp',['../lb__free_8hpp.html',1,'']]],
  ['lbeta_2ehpp_6946',['lbeta.hpp',['../fwd_2fun_2lbeta_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2lbeta_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2lbeta_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2lbeta_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2lbeta_8hpp.html',1,'(Global Namespace)']]],
  ['ldexp_2ehpp_6947',['ldexp.hpp',['../fwd_2fun_2ldexp_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2ldexp_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2ldexp_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2ldexp_8hpp.html',1,'(Global Namespace)']]],
  ['ldlt_5ffactor_2ehpp_6948',['LDLT_factor.hpp',['../prim_2fun_2_l_d_l_t__factor_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2_l_d_l_t__factor_8hpp.html',1,'(Global Namespace)']]],
  ['lgamma_2ehpp_6949',['lgamma.hpp',['../fwd_2fun_2lgamma_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2lgamma_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2lgamma_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2lgamma_8hpp.html',1,'(Global Namespace)']]],
  ['lgamma_5fstirling_2ehpp_6950',['lgamma_stirling.hpp',['../opencl_2kernels_2device__functions_2lgamma__stirling_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2lgamma__stirling_8hpp.html',1,'(Global Namespace)']]],
  ['lgamma_5fstirling_5fdiff_2ehpp_6951',['lgamma_stirling_diff.hpp',['../opencl_2kernels_2device__functions_2lgamma__stirling__diff_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2lgamma__stirling__diff_8hpp.html',1,'(Global Namespace)']]],
  ['linspaced_5farray_2ehpp_6952',['linspaced_array.hpp',['../linspaced__array_8hpp.html',1,'']]],
  ['linspaced_5fint_5farray_2ehpp_6953',['linspaced_int_array.hpp',['../linspaced__int__array_8hpp.html',1,'']]],
  ['linspaced_5frow_5fvector_2ehpp_6954',['linspaced_row_vector.hpp',['../linspaced__row__vector_8hpp.html',1,'']]],
  ['linspaced_5fvector_2ehpp_6955',['linspaced_vector.hpp',['../linspaced__vector_8hpp.html',1,'']]],
  ['lkj_5fcorr_5fcholesky_5flog_2ehpp_6956',['lkj_corr_cholesky_log.hpp',['../lkj__corr__cholesky__log_8hpp.html',1,'']]],
  ['lkj_5fcorr_5fcholesky_5flpdf_2ehpp_6957',['lkj_corr_cholesky_lpdf.hpp',['../lkj__corr__cholesky__lpdf_8hpp.html',1,'']]],
  ['lkj_5fcorr_5fcholesky_5frng_2ehpp_6958',['lkj_corr_cholesky_rng.hpp',['../lkj__corr__cholesky__rng_8hpp.html',1,'']]],
  ['lkj_5fcorr_5flog_2ehpp_6959',['lkj_corr_log.hpp',['../lkj__corr__log_8hpp.html',1,'']]],
  ['lkj_5fcorr_5flpdf_2ehpp_6960',['lkj_corr_lpdf.hpp',['../lkj__corr__lpdf_8hpp.html',1,'']]],
  ['lkj_5fcorr_5frng_2ehpp_6961',['lkj_corr_rng.hpp',['../lkj__corr__rng_8hpp.html',1,'']]],
  ['lkj_5fcov_5flog_2ehpp_6962',['lkj_cov_log.hpp',['../lkj__cov__log_8hpp.html',1,'']]],
  ['lkj_5fcov_5flpdf_2ehpp_6963',['lkj_cov_lpdf.hpp',['../lkj__cov__lpdf_8hpp.html',1,'']]],
  ['lmgamma_2ehpp_6964',['lmgamma.hpp',['../fwd_2fun_2lmgamma_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2lmgamma_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2lmgamma_8hpp.html',1,'(Global Namespace)']]],
  ['lmultiply_2ehpp_6965',['lmultiply.hpp',['../fwd_2fun_2lmultiply_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2lmultiply_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2lmultiply_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2lmultiply_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2lmultiply_8hpp.html',1,'(Global Namespace)']]],
  ['load_2ehpp_6966',['load.hpp',['../load_8hpp.html',1,'']]],
  ['log_2ehpp_6967',['log.hpp',['../fwd_2fun_2log_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log_8hpp.html',1,'(Global Namespace)']]],
  ['log10_2ehpp_6968',['log10.hpp',['../fwd_2fun_2log10_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log10_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log10_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log10_8hpp.html',1,'(Global Namespace)']]],
  ['log1m_2ehpp_6969',['log1m.hpp',['../fwd_2fun_2log1m_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2log1m_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log1m_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log1m_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log1m_8hpp.html',1,'(Global Namespace)']]],
  ['log1m_5fexp_2ehpp_6970',['log1m_exp.hpp',['../fwd_2fun_2log1m__exp_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2log1m__exp_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log1m__exp_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log1m__exp_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log1m__exp_8hpp.html',1,'(Global Namespace)']]],
  ['log1m_5finv_5flogit_2ehpp_6971',['log1m_inv_logit.hpp',['../fwd_2fun_2log1m__inv__logit_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2log1m__inv__logit_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log1m__inv__logit_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log1m__inv__logit_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log1m__inv__logit_8hpp.html',1,'(Global Namespace)']]],
  ['log1p_2ehpp_6972',['log1p.hpp',['../fwd_2fun_2log1p_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log1p_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log1p_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log1p_8hpp.html',1,'(Global Namespace)']]],
  ['log1p_5fexp_2ehpp_6973',['log1p_exp.hpp',['../fwd_2fun_2log1p__exp_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2log1p__exp_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log1p__exp_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log1p__exp_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log1p__exp_8hpp.html',1,'(Global Namespace)']]],
  ['log2_2ehpp_6974',['log2.hpp',['../fwd_2fun_2log2_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log2_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log2_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log2_8hpp.html',1,'(Global Namespace)']]],
  ['log_5fdeterminant_2ehpp_6975',['log_determinant.hpp',['../fwd_2fun_2log__determinant_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log__determinant_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__determinant_8hpp.html',1,'(Global Namespace)']]],
  ['log_5fdeterminant_5fldlt_2ehpp_6976',['log_determinant_ldlt.hpp',['../prim_2fun_2log__determinant__ldlt_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__determinant__ldlt_8hpp.html',1,'(Global Namespace)']]],
  ['log_5fdeterminant_5fspd_2ehpp_6977',['log_determinant_spd.hpp',['../prim_2fun_2log__determinant__spd_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__determinant__spd_8hpp.html',1,'(Global Namespace)']]],
  ['log_5fdiff_5fexp_2ehpp_6978',['log_diff_exp.hpp',['../fwd_2fun_2log__diff__exp_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2log__diff__exp_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log__diff__exp_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log__diff__exp_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__diff__exp_8hpp.html',1,'(Global Namespace)']]],
  ['log_5ffalling_5ffactorial_2ehpp_6979',['log_falling_factorial.hpp',['../fwd_2fun_2log__falling__factorial_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log__falling__factorial_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__falling__factorial_8hpp.html',1,'(Global Namespace)']]],
  ['log_5finv_5flogit_2ehpp_6980',['log_inv_logit.hpp',['../fwd_2fun_2log__inv__logit_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2log__inv__logit_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log__inv__logit_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log__inv__logit_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__inv__logit_8hpp.html',1,'(Global Namespace)']]],
  ['log_5finv_5flogit_5fdiff_2ehpp_6981',['log_inv_logit_diff.hpp',['../fwd_2fun_2log__inv__logit__diff_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2log__inv__logit__diff_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log__inv__logit__diff_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log__inv__logit__diff_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__inv__logit__diff_8hpp.html',1,'(Global Namespace)']]],
  ['log_5fmix_2ehpp_6982',['log_mix.hpp',['../fwd_2fun_2log__mix_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2log__mix_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log__mix_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__mix_8hpp.html',1,'(Global Namespace)']]],
  ['log_5fmodified_5fbessel_5ffirst_5fkind_2ehpp_6983',['log_modified_bessel_first_kind.hpp',['../log__modified__bessel__first__kind_8hpp.html',1,'']]],
  ['log_5frising_5ffactorial_2ehpp_6984',['log_rising_factorial.hpp',['../fwd_2fun_2log__rising__factorial_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log__rising__factorial_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__rising__factorial_8hpp.html',1,'(Global Namespace)']]],
  ['log_5fsoftmax_2ehpp_6985',['log_softmax.hpp',['../fwd_2fun_2log__softmax_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2log__softmax_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log__softmax_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log__softmax_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__softmax_8hpp.html',1,'(Global Namespace)']]],
  ['log_5fsum_5fexp_2ehpp_6986',['log_sum_exp.hpp',['../fwd_2fun_2log__sum__exp_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2log__sum__exp_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log__sum__exp_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log__sum__exp_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__sum__exp_8hpp.html',1,'(Global Namespace)']]],
  ['logb_2ehpp_6987',['logb.hpp',['../logb_8hpp.html',1,'']]],
  ['logical_5fand_2ehpp_6988',['logical_and.hpp',['../logical__and_8hpp.html',1,'']]],
  ['logical_5feq_2ehpp_6989',['logical_eq.hpp',['../logical__eq_8hpp.html',1,'']]],
  ['logical_5fgt_2ehpp_6990',['logical_gt.hpp',['../logical__gt_8hpp.html',1,'']]],
  ['logical_5fgte_2ehpp_6991',['logical_gte.hpp',['../logical__gte_8hpp.html',1,'']]],
  ['logical_5flt_2ehpp_6992',['logical_lt.hpp',['../logical__lt_8hpp.html',1,'']]],
  ['logical_5flte_2ehpp_6993',['logical_lte.hpp',['../logical__lte_8hpp.html',1,'']]],
  ['logical_5fnegation_2ehpp_6994',['logical_negation.hpp',['../logical__negation_8hpp.html',1,'']]],
  ['logical_5fneq_2ehpp_6995',['logical_neq.hpp',['../logical__neq_8hpp.html',1,'']]],
  ['logical_5for_2ehpp_6996',['logical_or.hpp',['../logical__or_8hpp.html',1,'']]],
  ['logistic_5fccdf_5flog_2ehpp_6997',['logistic_ccdf_log.hpp',['../logistic__ccdf__log_8hpp.html',1,'']]],
  ['logistic_5fcdf_2ehpp_6998',['logistic_cdf.hpp',['../opencl_2prim_2logistic__cdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2logistic__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['logistic_5fcdf_5flog_2ehpp_6999',['logistic_cdf_log.hpp',['../logistic__cdf__log_8hpp.html',1,'']]],
  ['logistic_5flccdf_2ehpp_7000',['logistic_lccdf.hpp',['../opencl_2prim_2logistic__lccdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2logistic__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['logistic_5flcdf_2ehpp_7001',['logistic_lcdf.hpp',['../opencl_2prim_2logistic__lcdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2logistic__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['logistic_5flog_2ehpp_7002',['logistic_log.hpp',['../logistic__log_8hpp.html',1,'']]],
  ['logistic_5flpdf_2ehpp_7003',['logistic_lpdf.hpp',['../opencl_2prim_2logistic__lpdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2logistic__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['logistic_5frng_2ehpp_7004',['logistic_rng.hpp',['../logistic__rng_8hpp.html',1,'']]],
  ['logit_2ehpp_7005',['logit.hpp',['../fwd_2fun_2logit_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2logit_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2logit_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2logit_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2logit_8hpp.html',1,'(Global Namespace)']]],
  ['loglogistic_5fcdf_2ehpp_7006',['loglogistic_cdf.hpp',['../loglogistic__cdf_8hpp.html',1,'']]],
  ['loglogistic_5flog_2ehpp_7007',['loglogistic_log.hpp',['../loglogistic__log_8hpp.html',1,'']]],
  ['loglogistic_5flpdf_2ehpp_7008',['loglogistic_lpdf.hpp',['../loglogistic__lpdf_8hpp.html',1,'']]],
  ['loglogistic_5frng_2ehpp_7009',['loglogistic_rng.hpp',['../loglogistic__rng_8hpp.html',1,'']]],
  ['lognormal_5fccdf_5flog_2ehpp_7010',['lognormal_ccdf_log.hpp',['../lognormal__ccdf__log_8hpp.html',1,'']]],
  ['lognormal_5fcdf_2ehpp_7011',['lognormal_cdf.hpp',['../opencl_2prim_2lognormal__cdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2lognormal__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['lognormal_5fcdf_5flog_2ehpp_7012',['lognormal_cdf_log.hpp',['../lognormal__cdf__log_8hpp.html',1,'']]],
  ['lognormal_5flccdf_2ehpp_7013',['lognormal_lccdf.hpp',['../opencl_2prim_2lognormal__lccdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2lognormal__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['lognormal_5flcdf_2ehpp_7014',['lognormal_lcdf.hpp',['../opencl_2prim_2lognormal__lcdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2lognormal__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['lognormal_5flog_2ehpp_7015',['lognormal_log.hpp',['../lognormal__log_8hpp.html',1,'']]],
  ['lognormal_5flpdf_2ehpp_7016',['lognormal_lpdf.hpp',['../opencl_2prim_2lognormal__lpdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2lognormal__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['lognormal_5frng_2ehpp_7017',['lognormal_rng.hpp',['../lognormal__rng_8hpp.html',1,'']]],
  ['lub_5fconstrain_2ehpp_7018',['lub_constrain.hpp',['../opencl_2prim_2lub__constrain_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2lub__constrain_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2lub__constrain_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2lub__constrain_8hpp.html',1,'(Global Namespace)']]],
  ['lub_5ffree_2ehpp_7019',['lub_free.hpp',['../lub__free_8hpp.html',1,'']]]
];
