var searchData=
[
  ['dae_2ehpp_6621',['dae.hpp',['../dae_8hpp.html',1,'']]],
  ['dae_5fsystem_2ehpp_6622',['dae_system.hpp',['../dae__system_8hpp.html',1,'']]],
  ['ddv_5fvari_2ehpp_6623',['ddv_vari.hpp',['../ddv__vari_8hpp.html',1,'']]],
  ['deep_5fcopy_5fvars_2ehpp_6624',['deep_copy_vars.hpp',['../deep__copy__vars_8hpp.html',1,'']]],
  ['derivative_2ehpp_6625',['derivative.hpp',['../derivative_8hpp.html',1,'']]],
  ['determinant_2ehpp_6626',['determinant.hpp',['../fwd_2fun_2determinant_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2determinant_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2determinant_8hpp.html',1,'(Global Namespace)']]],
  ['developer_5fdoc_2emd_6627',['developer_doc.md',['../developer__doc_8md.html',1,'']]],
  ['diag_5finv_2ehpp_6628',['diag_inv.hpp',['../diag__inv_8hpp.html',1,'']]],
  ['diag_5fmatrix_2ehpp_6629',['diag_matrix.hpp',['../opencl_2prim_2diag__matrix_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2diag__matrix_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2diag__matrix_8hpp.html',1,'(Global Namespace)']]],
  ['diag_5fpost_5fmultiply_2ehpp_6630',['diag_post_multiply.hpp',['../opencl_2prim_2diag__post__multiply_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2diag__post__multiply_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2diag__post__multiply_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2diag__post__multiply_8hpp.html',1,'(Global Namespace)']]],
  ['diag_5fpre_5fmultiply_2ehpp_6631',['diag_pre_multiply.hpp',['../opencl_2prim_2diag__pre__multiply_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2diag__pre__multiply_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2diag__pre__multiply_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2diag__pre__multiply_8hpp.html',1,'(Global Namespace)']]],
  ['diagonal_2ehpp_6632',['diagonal.hpp',['../opencl_2kernel__generator_2diagonal_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2diagonal_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2diagonal_8hpp.html',1,'(Global Namespace)']]],
  ['digamma_2ehpp_6633',['digamma.hpp',['../fwd_2fun_2digamma_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2digamma_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2digamma_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2digamma_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2digamma_8hpp.html',1,'(Global Namespace)']]],
  ['dims_2ehpp_6634',['dims.hpp',['../opencl_2prim_2dims_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2dims_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2dims_8hpp.html',1,'(Global Namespace)']]],
  ['dirichlet_5flog_2ehpp_6635',['dirichlet_log.hpp',['../dirichlet__log_8hpp.html',1,'']]],
  ['dirichlet_5flpdf_2ehpp_6636',['dirichlet_lpdf.hpp',['../opencl_2prim_2dirichlet__lpdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2dirichlet__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['dirichlet_5flpmf_2ehpp_6637',['dirichlet_lpmf.hpp',['../dirichlet__lpmf_8hpp.html',1,'']]],
  ['dirichlet_5frng_2ehpp_6638',['dirichlet_rng.hpp',['../dirichlet__rng_8hpp.html',1,'']]],
  ['discrete_5frange_5fccdf_5flog_2ehpp_6639',['discrete_range_ccdf_log.hpp',['../discrete__range__ccdf__log_8hpp.html',1,'']]],
  ['discrete_5frange_5fcdf_2ehpp_6640',['discrete_range_cdf.hpp',['../discrete__range__cdf_8hpp.html',1,'']]],
  ['discrete_5frange_5fcdf_5flog_2ehpp_6641',['discrete_range_cdf_log.hpp',['../discrete__range__cdf__log_8hpp.html',1,'']]],
  ['discrete_5frange_5flccdf_2ehpp_6642',['discrete_range_lccdf.hpp',['../discrete__range__lccdf_8hpp.html',1,'']]],
  ['discrete_5frange_5flcdf_2ehpp_6643',['discrete_range_lcdf.hpp',['../discrete__range__lcdf_8hpp.html',1,'']]],
  ['discrete_5frange_5flog_2ehpp_6644',['discrete_range_log.hpp',['../discrete__range__log_8hpp.html',1,'']]],
  ['discrete_5frange_5flpmf_2ehpp_6645',['discrete_range_lpmf.hpp',['../discrete__range__lpmf_8hpp.html',1,'']]],
  ['discrete_5frange_5frng_2ehpp_6646',['discrete_range_rng.hpp',['../discrete__range__rng_8hpp.html',1,'']]],
  ['disjunction_2ehpp_6647',['disjunction.hpp',['../disjunction_8hpp.html',1,'']]],
  ['distance_2ehpp_6648',['distance.hpp',['../opencl_2prim_2distance_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2distance_8hpp.html',1,'(Global Namespace)']]],
  ['distribution_5ftests_2emd_6649',['distribution_tests.md',['../distribution__tests_8md.html',1,'']]],
  ['divide_2ehpp_6650',['divide.hpp',['../opencl_2prim_2divide_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2divide_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2divide_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2divide_8hpp.html',1,'(Global Namespace)']]],
  ['divide_5fcolumns_2ehpp_6651',['divide_columns.hpp',['../opencl_2kernels_2divide__columns_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2divide__columns_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2divide__columns_8hpp.html',1,'(Global Namespace)']]],
  ['domain_5ferror_2ehpp_6652',['domain_error.hpp',['../domain__error_8hpp.html',1,'']]],
  ['domain_5ferror_5fvec_2ehpp_6653',['domain_error_vec.hpp',['../domain__error__vec_8hpp.html',1,'']]],
  ['dot_2ehpp_6654',['dot.hpp',['../dot_8hpp.html',1,'']]],
  ['dot_5fproduct_2ehpp_6655',['dot_product.hpp',['../opencl_2prim_2dot__product_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2dot__product_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2dot__product_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2dot__product_8hpp.html',1,'(Global Namespace)']]],
  ['dot_5fself_2ehpp_6656',['dot_self.hpp',['../opencl_2prim_2dot__self_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2dot__self_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2dot__self_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2dot__self_8hpp.html',1,'(Global Namespace)']]],
  ['double_5fd_2ehpp_6657',['double_d.hpp',['../double__d_8hpp.html',1,'']]],
  ['double_5fexponential_5fccdf_5flog_2ehpp_6658',['double_exponential_ccdf_log.hpp',['../double__exponential__ccdf__log_8hpp.html',1,'']]],
  ['double_5fexponential_5fcdf_2ehpp_6659',['double_exponential_cdf.hpp',['../opencl_2prim_2double__exponential__cdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2double__exponential__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['double_5fexponential_5fcdf_5flog_2ehpp_6660',['double_exponential_cdf_log.hpp',['../double__exponential__cdf__log_8hpp.html',1,'']]],
  ['double_5fexponential_5flccdf_2ehpp_6661',['double_exponential_lccdf.hpp',['../opencl_2prim_2double__exponential__lccdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2double__exponential__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['double_5fexponential_5flcdf_2ehpp_6662',['double_exponential_lcdf.hpp',['../opencl_2prim_2double__exponential__lcdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2double__exponential__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['double_5fexponential_5flog_2ehpp_6663',['double_exponential_log.hpp',['../double__exponential__log_8hpp.html',1,'']]],
  ['double_5fexponential_5flpdf_2ehpp_6664',['double_exponential_lpdf.hpp',['../opencl_2prim_2double__exponential__lpdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2double__exponential__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['double_5fexponential_5frng_2ehpp_6665',['double_exponential_rng.hpp',['../double__exponential__rng_8hpp.html',1,'']]],
  ['dv_5fvari_2ehpp_6666',['dv_vari.hpp',['../dv__vari_8hpp.html',1,'']]],
  ['dvd_5fvari_2ehpp_6667',['dvd_vari.hpp',['../dvd__vari_8hpp.html',1,'']]],
  ['dvv_5fvari_2ehpp_6668',['dvv_vari.hpp',['../dvv__vari_8hpp.html',1,'']]]
];
